const db = require('../config/db')

// db('perfis')
//     .then(res => console.log(res))
//     .catch(err => console.log(err.sqlMessage))
//     .finally(() => db.destroy())

// db('perfis')
//     .then(res => res.map(p => p.nome))
//     .then(nomes => console.log(nomes))
//     .catch(err => console.log(err.sqlMessage))
//     .finally(() => db.destroy())

// db('perfis').select('nome', 'id')
//     .then(res => console.log(res))
//     .catch(err => console.log(err.sqlMessage))
//     .finally(() => db.destroy())

// db.select('nome', 'id')
//     .from('perfis')
//     .then(res => console.log(res))
//     .catch(err => console.log(err.sqlMessage))
//     .finally(() => db.destroy())

// db.select('nome', 'id')
//     .from('perfis')
//     .limit(4).offset(2)
//     .then(res => console.log(res))
//     .catch(err => console.log(err.sqlMessage))
//     .finally(() => db.destroy())

db('perfis')
    //.where({ id: 2 })
    //.where('id', '=', 3)
    //.where('nome', 'like', 'ad%')
    //.where('nome', 'like', '%root%')
    //.whereNot('nome', 'like', '%root%')
    .whereIn('id', [1, 2, 3])
    //.first()
    .then(res => console.log(res))
    .catch(err => console.log(err.sqlMessage))
    .finally(() => db.destroy())
    
